#!/bin/sh
#
# postgreSQL.init This shell script takes care of starting and stopping
#               the PostgreSQL postmaster.
#

# Source function library.
. /etc/rc.d/init.d/functions

WXDUSER=mikef

# See how we were called.
case "$1" in
  start)
        # Start daemons.
        echo -n "Starting wxd Weather daemon:"
        if [ -z "`pidofproc wxd`" ]
        then
                su $WXDUSER -c "/usr/local/sbin/wxd"
                echo -n " wxd"
        else
                echo -n " (already running)"
        fi
        echo
        touch /var/lock/subsys/wxd
        ;;
  stop)
        # Stop daemons.
        echo -n "Shutting down wxd Weather daemon: "
        killall -TERM wxd 2>/dev/null
        echo
        rm -f /var/lock/subsys/wxd
        ;;
  *)
        echo "Usage: wxd {start|stop}"
        exit 1
esac

exit 0

